### PR TITLE
Chrome allow additional options and allow redirecting child output

### PR DESCRIPTION
**Pull request by bogdanRada**
- Allow2 additional options to be passed to chrome and Casper 
 I need this functionality to be able to pass these options to chrome 
    '--ignore-certificate-errors',
   '--ignore-urlfetcher-cert-requests'
- Also ability to redirect child output diffrently . I need this because i want child stderr to write to stdout 

Please let me know if any changes are needed. Thank you

### CODE REVIEW

**Comment by bogdanRada** [comment]
any updates on this? I really need to possibility to pass additional options to the chrome driver at least.

**Comment by paps** [comment]
Hey, sorry for the delay and thanks for the PR. I don't see why I would not merge this :)

**Comment by bogdanRada** [comment]
hello @paps , thanks for merging this into master. 
Can this also be released on `https://yarnpkg.com/en/package/nickjs` ? I still see version 0.3.6. Can we bump it to 0.3.7 please? Thank you very much

**Comment by paps** [comment]
Done. 0.3.7 is up

**Pull request merged**
